#./scripts/lod/demos/baseLODController.gd
class_name BaseLODController extends Node

@export var manager: ChunkManager

@export var max_upgrades_per_frame := 8
@export var max_downgrades_per_frame := 16

## Desired LODs generated by this controller.
## Child controllers populate this every update.
var desired_lods : Dictionary = {}
## Previous frame's requests.
var previous_lods : Dictionary = {}


# ==================================================
# INITIALIZATION
# ==================================================

func _ready() -> void:

	if not manager:
		manager = get_parent() as ChunkManager

	if not manager and get_parent():
		manager = get_parent().get_parent() as ChunkManager

	if not manager:
		push_error("BaseLODController: Missing ChunkManager.")


# ==================================================
# PUBLIC API
# ==================================================

func clear_requests() -> void:
	desired_lods.clear()


func request_lod(
	coord: Vector3i,
	level: int
) -> void:
	desired_lods[coord] = level


func flush() -> void:
	var upgrades := 0
	var downgrades := 0

	#
	# Evaluate every requested coordinate.
	#
	for coord in desired_lods:

		var desired_level : int = desired_lods[coord]
		var current_level : int = (
			manager.context.index.get_highest_existing_lod(
				coord
			)
		)
		if desired_level == current_level:
			continue

		#
		# Upgrade
		#
		if desired_level > current_level:

			if upgrades >= max_upgrades_per_frame:
				continue

			_request_upgrade(
				coord,
				current_level,
				current_level + 1
			)

			upgrades += 1

		#
		# Downgrade
		#
		else:

			if downgrades >= max_downgrades_per_frame:
				continue

			_request_downgrade(
				coord,
				current_level,
				current_level - 1
			)

			downgrades += 1
	#
	# Anything requested last frame but missing now
	# should gracefully return to LOD 0.
	#
	for coord in previous_lods:

		if desired_lods.has(coord):
			continue

		var current_level := manager.context.index.get_highest_existing_lod(coord)

		if current_level == 0:
			continue

		if downgrades >= max_downgrades_per_frame:
			break

		_request_downgrade(
			coord,
			current_level,
			0
		)

		downgrades += 1


	previous_lods = desired_lods.duplicate()


# ==================================================
# INTERNAL
# ==================================================

func _request_upgrade(
	coord: Vector3i,
	_current_level: int,
	target_level: int
) -> void:
	manager.set_authorized_lod(
		coord,
		target_level
	)
	if target_level > _current_level:
		manager.subdivision_requested.emit(
			coord,
			target_level
		)


func _request_downgrade(
	coord: Vector3i,
	_current_level: int,
	target_level: int
) -> void:
	manager.set_authorized_lod(
		coord,
		target_level
	)
	if target_level - 1 >= 0 and target_level < _current_level:
		manager.merge_requested.emit(
			coord
		)
